FROM node:latest

RUN npm install -g create-react-app | mkdir -p /usr/src/app/new_pro

WORKDIR /usr/src/app/new_pro

RUN create-react-app new_pro


# this docker file creates new image from node:latest image installs create-react-app makes new directory cd to that directory and creates new reactjs project
