#!/bin/bash
#
# This is a rather minimal example Argbash potential
# Example taken from http://argbash.readthedocs.io/en/stable/example.html
#
# ARG_OPTIONAL_SINGLE([build-create],[b],[build from base image and create new reactjs project])
# ARG_OPTIONAL_SINGLE([detach-create],[d],[create new reactjs project from existing image])
# ARG_OPTIONAL_BOOLEAN([print],[],[Help using react_create[reactnew]])
# ARG_POSITIONAL_SINGLE([project-path],[path to the new project folder],[])
# ARG_HELP([The general script's help msg])
# ARGBASH_GO()
# needed because of Argbash --> m4_ignore([
### START OF CODE GENERATED BY Argbash v2.8.1 one line above ###
# Argbash is a bash code generator used to get arguments parsing right.
# Argbash is FREE SOFTWARE, see https://argbash.io for more info
# Generated online by https://argbash.io/generate


die()
{
	local _ret=$2
	test -n "$_ret" || _ret=1
	test "$_PRINT_HELP" = yes && print_help >&2
	echo "$1" >&2
	exit ${_ret}
}


begins_with_short_option()
{
	local first_option all_short_options='bdh'
	first_option="${1:0:1}"
	test "$all_short_options" = "${all_short_options/$first_option/}" && return 1 || return 0
}

# THE DEFAULTS INITIALIZATION - POSITIONALS
_positionals=()
# THE DEFAULTS INITIALIZATION - OPTIONALS
_arg_build_create=
_arg_detach_create=
_arg_print="off"


print_help()
{
	printf '%s\n' "The general script's help msg"
	printf 'Usage: %s [-b|--build-create <arg>] [-d|--detach-create <arg>] [--(no-)print] [-h|--help] <project-path>\n' "$0"
	printf '\t%s\n' "<project-path>: path to the new project folder"
	printf '\t%s\n' "-b, --build-create: build from base image and create new reactjs project (no default)"
	printf '\t%s\n' "-d, --detach-create: create new reactjs project from existing image (no default)"
	printf '\t%s\n' "--print, --no-print: Help using react_create[reactnew] (off by default)"
	printf '\t%s\n' "-h, --help: Prints help"
}


parse_commandline()
{
	_positionals_count=0
	while test $# -gt 0
	do
		_key="$1"
		case "$_key" in
			-b|--build-create)
				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
				_arg_build_create="$2"
				shift
				;;
			--build-create=*)
				_arg_build_create="${_key##--build-create=}"
				;;
			-b*)
				_arg_build_create="${_key##-b}"
				;;
			-d|--detach-create)
				test $# -lt 2 && die "Missing value for the optional argument '$_key'." 1
				_arg_detach_create="$2"
				shift
				;;
			--detach-create=*)
				_arg_detach_create="${_key##--detach-create=}"
				;;
			-d*)
				_arg_detach_create="${_key##-d}"
				;;
			--no-print|--print)
				_arg_print="on"
				test "${1:0:5}" = "--no-" && _arg_print="off"
				;;
			-h|--help)
				print_help
				exit 0
				;;
			-h*)
				print_help
				exit 0
				;;
			*)
				_last_positional="$1"
				_positionals+=("$_last_positional")
				_positionals_count=$((_positionals_count + 1))
				;;
		esac
		shift
	done
}


handle_passed_args_count()
{
	local _required_args_string="'project-path'"
	test "${_positionals_count}" -ge 1 || _PRINT_HELP=yes die "FATAL ERROR: Not enough positional arguments - we require exactly 1 (namely: $_required_args_string), but got only ${_positionals_count}." 1
	test "${_positionals_count}" -le 1 || _PRINT_HELP=yes die "FATAL ERROR: There were spurious positional arguments --- we expect exactly 1 (namely: $_required_args_string), but got ${_positionals_count} (the last one was: '${_last_positional}')." 1
}


assign_positional_args()
{
	local _positional_name _shift_for=$1
	_positional_names="_arg_project_path "

	shift "$_shift_for"
	for _positional_name in ${_positional_names}
	do
		test $# -gt 0 || break
		eval "$_positional_name=\${1}" || die "Error during argument parsing, possibly an Argbash bug." 1
		shift
	done
}

parse_commandline "$@"
handle_passed_args_count
assign_positional_args 1 "${_positionals[@]}"

# OTHER STUFF GENERATED BY Argbash

### END OF CODE GENERATED BY Argbash (sortof) ### ])
# [ <-- needed because of Argbash


echo "Value of --buid-create: $_arg_build_create"
echo "Value of --detach-create: $_arg_detach_create"
echo "print is $_arg_print"
echo "Value of positional-arg: $_arg_project-path"

# ] <-- needed because of Argbash
